@startuml

actor user as "user"

rectangle Database

rectangle "program" {
    usecase UC4 as "Get population of country"

    usecase UCa as "print population"


    user - UC4

    UC4 ..> UCa


    UC4 - Database

}

@enduml